### ISSUE TITLE
Guard::Compass failed to achieve its <run_on_change>

### ISSUE THREAD

**Issue by KasperTidemann** [guard/guard-compass#10]
Hi guys,

I'm getting an error using guard-compass. In my Guardfile, I have the following:

```
guard 'compass' do
  watch(/^src\/sass\/(.*)\.s[ac]ss/)
end
```

The error I'm getting is this:

```
ERROR: Guard::Compass failed to achieve its <run_on_change>, exception was:
Compass::Error: Nothing to compile. If you're trying to start a new project, you have left off the directory argument.
Run "compass -h" to get help.
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/compass-0.12.2/lib/compass/commands/update_project.rb:53:in `check_for_sass_files!'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/compass-0.12.2/lib/compass/commands/update_project.rb:43:in `perform'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/compass-0.12.2/lib/compass/commands/base.rb:18:in `execute'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/compass-0.12.2/lib/compass/commands/project_base.rb:19:in `execute'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-compass-0.0.6/lib/guard/compass.rb:47:in `run_on_change'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard/runner.rb:90:in `block in run_supervised_task'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard/runner.rb:88:in `catch'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard/runner.rb:88:in `run_supervised_task'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard/runner.rb:137:in `block in run_first_task_found'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard/runner.rb:135:in `each'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard/runner.rb:135:in `run_first_task_found'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard/runner.rb:70:in `block in run_on_changes'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard/runner.rb:161:in `block (3 levels) in scoped_guards'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard/runner.rb:160:in `each'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard/runner.rb:160:in `block (2 levels) in scoped_guards'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard/runner.rb:159:in `catch'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard/runner.rb:159:in `block in scoped_guards'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard/runner.rb:158:in `each'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard/runner.rb:158:in `scoped_guards'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard/runner.rb:63:in `run_on_changes'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard.rb:110:in `block (2 levels) in setup_listener'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard.rb:323:in `block in within_preserved_state'
<internal:prelude>:10:in `synchronize'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard.rb:320:in `within_preserved_state'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/guard-1.2.3/lib/guard.rb:109:in `block in setup_listener'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/listen-0.4.7/lib/listen/listener.rb:190:in `call'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/listen-0.4.7/lib/listen/listener.rb:190:in `on_change'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/listen-0.4.7/lib/listen/listener.rb:199:in `block in initialize_adapter'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/listen-0.4.7/lib/listen/adapter.rb:162:in `call'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/listen-0.4.7/lib/listen/adapter.rb:162:in `poll_changed_dirs'
/Users/kasper/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/listen-0.4.7/lib/listen/adapters/darwin.rb:28:in `block in start'

Guard::Compass has just been fired
```

I am using Guard version 1.2.3 and Compass 0.12.2. Any idea what's wrong here?

**Comment by zx1986** [comment]
I got exactly the same error!
here is my env:

config.rb

``` ruby
# Require any additional compass plugins here.
require 'bootstrap-sass'

# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "assets/stylesheets"
sass_dir = "assets/sass"
images_dir = "assets/images"
javascripts_dir = "assets/javascripts"
```

Guardfile

``` ruby
# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'livereload' do
  watch(%r{.+\.(php|html|js|css)})
end

guard 'compass' do
  watch(/assets\/sass\/(.*)\.s[ac]ss/)
end

guard 'coffeescript', :input => 'assets/coffee', :output => 'assets/js', :hide_success => true
```

Gemfiles

``` ruby
source "http://rubygems.org"
source "http://gems.rubyforge.org"
source "http://gemcutter.org"

gem 'compass'
gem 'rb-inotify'
gem 'guard'
gem 'guard-livereload'
gem 'guard-coffeescript'
gem 'guard-compass'
gem 'guard-sass'
gem 'sass-rails', '~> 3.1'
gem 'bootstrap-sass', '~> 2.1.1.0'
```

gems version

``` ruby
Gems included by the bundle:
  * actionpack (3.2.9)
  * activemodel (3.2.9)
  * activesupport (3.2.9)
  * addressable (2.3.2)
  * bootstrap-sass (2.1.1.0)
  * builder (3.0.4)
  * bundler (1.1.4)
  * chunky_png (1.2.6)
  * coderay (1.0.8)
  * coffee-script (2.2.0)
  * coffee-script-source (1.4.0)
  * compass (0.12.2)
  * em-websocket (0.3.8)
  * erubis (2.7.0)
  * eventmachine (1.0.0)
  * execjs (1.4.0)
  * ffi (1.1.5)
  * fssm (0.2.9)
  * guard (1.5.4)
  * guard-coffeescript (1.2.1)
  * guard-compass (0.0.6)
  * guard-livereload (1.1.0)
  * guard-sass (1.0.1)
  * hike (1.2.1)
  * i18n (0.6.1)
  * journey (1.0.4)
  * json (1.7.5)
  * listen (0.5.3)
  * lumberjack (1.0.2)
  * method_source (0.8.1)
  * multi_json (1.3.7)
  * pry (0.9.10)
  * rack (1.4.1)
  * rack-cache (1.2)
  * rack-ssl (1.3.2)
  * rack-test (0.6.2)
  * railties (3.2.9)
  * rake (10.0.0)
  * rb-inotify (0.8.8)
  * rdoc (3.12)
  * sass (3.2.3)
  * sass-rails (3.2.5)
  * slop (3.3.3)
  * sprockets (2.2.1)
  * thor (0.16.0)
  * tilt (1.3.3)
```

the error

```
14:15:56 - ERROR - Guard::Compass failed to achieve its <run_on_change>, exception was:                               [29/1923]
> [#] Compass::Error: Nothing to compile. If you're trying to start a new project, you have left off the directory argument.
> [#] Run "compass -h" to get help.
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/compass-0.12.2/lib/compass/commands/update_project.rb:53:in `check_for_sass_file
s!'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/compass-0.12.2/lib/compass/commands/update_project.rb:43:in `perform'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/compass-0.12.2/lib/compass/commands/base.rb:18:in `execute'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/compass-0.12.2/lib/compass/commands/project_base.rb:19:in `execute'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/guard-compass-0.0.6/lib/guard/compass.rb:47:in `run_on_change'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/guard-1.5.4/lib/guard/runner.rb:99:in `block in run_supervised_task'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/guard-1.5.4/lib/guard/runner.rb:97:in `catch'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/guard-1.5.4/lib/guard/runner.rb:97:in `run_supervised_task'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/guard-1.5.4/lib/guard/runner.rb:146:in `block in run_first_task_found'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/guard-1.5.4/lib/guard/runner.rb:144:in `each'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/guard-1.5.4/lib/guard/runner.rb:144:in `run_first_task_found'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/guard-1.5.4/lib/guard/runner.rb:80:in `block in run_on_changes'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/guard-1.5.4/lib/guard/runner.rb:170:in `block (3 levels) in scoped_guards'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/guard-1.5.4/lib/guard/runner.rb:167:in `each'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/guard-1.5.4/lib/guard/runner.rb:167:in `scoped_guards'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/guard-1.5.4/lib/guard/runner.rb:72:in `run_on_changes'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/guard-1.5.4/lib/guard.rb:114:in `block (2 levels) in setup_listener'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/guard-1.5.4/lib/guard.rb:334:in `block in within_preserved_state'
> [#] <internal:prelude>:10:in `synchronize'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/guard-1.5.4/lib/guard.rb:331:in `within_preserved_state'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/guard-1.5.4/lib/guard.rb:113:in `block in setup_listener'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/listen-0.5.3/lib/listen/listener.rb:190:in `call'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/listen-0.5.3/lib/listen/listener.rb:190:in `on_change'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/listen-0.5.3/lib/listen/listener.rb:199:in `block in initialize_adapter'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/listen-0.5.3/lib/listen/adapter.rb:196:in `call'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/listen-0.5.3/lib/listen/adapter.rb:196:in `report_changes'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/listen-0.5.3/lib/listen/adapter.rb:208:in `poll_changed_dirs'
> [#] /usr/local/rvm/gems/ruby-1.9.3-p125/gems/listen-0.5.3/lib/listen/adapters/linux.rb:48:in `block in start'
14:15:56 - INFO - Guard::Compass has just been fired
```

## but after reload guard, my scss compiled again ....

**Comment by rymai** [comment]
Hi guys, first, please:
- Update guard and guard-compass (`bundle update guard guard-compass`)
- Make sure you check settings in both the `Guardfile` AND in the `config.rb` (it will give this error if the compass config is pointing to the wrong stylesheets directory)
- Make sure `compass watch` works
- Make sure your regex is good in the Guardfile

If you still have any issues, please give as much details as possible, thanks!
